name: CI Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: ci-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: All Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: pw-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            pw-${{ runner.os }}-

      - name: Install Playwright Chromium
        run: npx playwright install chromium

      - name: Build
        run: npm run build

      - name: ESLint
        run: npm run lint

      - name: TypeScript
        run: npx tsc --noEmit

      - name: Tests (unit + E2E)
        run: npm run test:e2e

      - name: Compute artifact name
        if: failure()
        id: artifact_name
        run: |
          SAFE_REF=${GITHUB_REF_NAME//\//-}
          echo "value=test-artifacts-${SAFE_REF}" >> "$GITHUB_OUTPUT"

      - name: Upload test artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.artifact_name.outputs.value }}
          path: |
            test-results/
            playwright-report/
          if-no-files-found: ignore
